FROM centos:7
MAINTAINER Viktor Hansson "viktor.hansson@dataductus.se"

# Install the Saltstack 2016.11 minion
RUN yum install -y https://repo.saltstack.com/yum/redhat/salt-repo-2016.11-2.el7.noarch.rpm && \
	yum clean expire-cache && \
	yum install -y salt-master salt-minion && \
	yum clean all

# Add salt config files
ADD etc/master /etc/salt/master
ADD etc/minion /etc/salt/minion

# Exposing salt master ports
EXPOSE 4505 4506

# Add and set start script
ADD start.sh /start.sh
CMD ["bash", "start.sh"]

